project:
  type: website
  output-dir: docs

website:
  title: "Names Are Hard"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sheitin
format:
  html:
    theme: yeti
    css: styles.css



  